CURRENCY_CODES = {
    "Australia": ["Dollar", "AUD", "$"],
    "Great Britain": ["Pound", "GBP", "£"],
    "Euro": ["Euro", "EUR", "€"],
    "Japan": ["Yen", "JPY", "¥"],
    "Switzerland": ["Franc", "CHF"],
    "USA": ["Dollar", "USD", "$"],
    "Afghanistan": ["Afghani", "AFN", "؋"],
    "Albania": ["Lek", "ALL"],
    "Algeria": ["Dinar", "DZD", "د.ج"],
    "Angola": ["Kwanza", "AOA"],
    "Argentina": ["Peso", "ARS", "$"],
    "Armenia": ["Dram", "AMD", "֏"],
    "Aruba": ["Florin", "AWG"],
    "Azerbaijan": ["New Manat", "AZN", "₼"],
    "Bahamas": ["Dollar", "BSD", "$"],
    "Bahrain": ["Dinar", "BHD", ".د.ب"],
    "Bangladesh": ["Taka", "BDT", "৳"],
    "Barbados": ["Dollar", "BBD", "$"],
    "Belarus": ["Ruble", "BYR"],
    "Belize": ["Dollar", "BZD", "$"],
    "Bermuda": ["Dollar", "BMD", "$"],
    "Bhutan": ["Ngultrum", "BTN"],
    "Bolivia": ["Boliviano", "BOB"],
    "Bosnia": ["Mark", "BAM"],
    "Botswana": ["Pula", "BWP"],
    "Brazil": ["Real", "BRL", "R$"],
    "Brunei": ["Dollar", "BND", "$"],
    "Bulgaria": ["Lev", "BGN", "лв"],
    "Burundi": ["Franc", "BIF"],
    "CFA Franc BCEAO": ["Franc", "XOF"],
    "CFA Franc BEAC": ["Franc", "XAF"],
    "CFP Franc": ["Franc", "XPF"],
    "Cambodia": ["Riel", "KHR", "៛"],
    "Canada": ["Dollar", "CAD", "$"],
    "Cape Verde": ["Escudo", "CVE"],
    "Cayman Islands": ["Dollar", "KYD", "$"],
    "Chile": ["Peso", "CLP", "$"],
    "China": ["Yuan/Renminbi", "CNY", "¥"],
    "Colombia": ["Peso", "COP", "$"],
    "Comoros": ["Franc", "KMF"],
    "Congo": ["Franc", "CDF"],
    "Costa Rica": ["Colon", "CRC", "₡"],
    "Croatia": ["Kuna", "HRK"],
    "Cuba Convertible": ["Peso", "CUC", "$"],
    "Cuba": ["Peso", "CUP", "$"],
    "Cyprus": ["Pound", "CYP", "£"],
    "Czech Republic": ["Koruna", "CZK", "Kč"],
    "Denmark": ["Krone", "DKK"],
    "Djibouti": ["Franc", "DJF"],
    "Dominican Republic": ["Peso", "DOP", "$"],
    "East Caribbean": ["Dollar", "XCD", "$"],
    "Egypt": ["Pound", "EGP", "£"],
    "El Salvador": ["Colon", "SVC", "$"],
    "Estonia": ["Kroon", "EEK"],
    "Ethiopia": ["Birr", "ETB"],
    "Falkland Islands": ["Pound", "FKP", "£"],
    "Fiji": ["Dollar", "FJD", "$"],
    "Gambia": ["Dalasi", "GMD"],
    "Georgia": ["Lari", "GEL", "₾"],
    "Ghana": ["New Cedi", "GHS", "GH₵"],
    "Gibraltar": ["Pound", "GIP", "£"],
    "Guatemala": ["Quetzal", "GTQ"],
    "Guinea": ["Franc", "GNF"],
    "Guyana": ["Dollar", "GYD", "$"],
    "Haiti": ["Gourde", "HTG"],
    "Honduras": ["Lempira", "HNL"],
    "Hong Kong": ["Dollar", "HKD", "$"],
    "Hungary": ["Forint", "HUF"],
    "Iceland": ["Krona", "ISK"],
    "India": ["Rupee", "INR", "₹"],
    "Indonesia": ["Rupiah", "IDR"],
    "Iran": ["Rial", "IRR", "﷼"],
    "Iraq": ["Dinar", "IQD", "ع.د"],
    "Ireland": ["Pound", "IED", "£"],
    "Israel": ["New Shekel", "ILS", "₪"],
    "Italy": ["Lira", "ITL", "₤"],
    "Jamaica": ["Dollar", "JMD", "$"],
    "Jordan": ["Dinar", "JOD", "د.ا"],
    "Kazakhstan": ["Tenge", "KZT", "₸"],
    "Kenya": ["Shilling", "KES"],
    "Kuwait": ["Dinar", "KWD", "د.ك"],
    "Kyrgyzstan": ["Som", "KGS", "с"],
    "Laos": ["Kip", "LAK", "₭"],
    "Latvia": [
        "Lats",
        "LVL",
    ],
    "Lebanon": ["Pound", "LBP", "ل.ل"],
    "Lesotho": ["Loti", "LSL"],
    "Liberia": ["Dollar", "LRD", "$"],
    "Libya": ["Dinar", "LYD", "ل.د"],
    "Lithuania": ["Litas", "LTL"],
    "Luxembourg": ["Franc", "LUF"],
    "Macau": ["Pataca", "MOP", "MOP$"],
    "Macedonia": ["Denar", "MKD", "ден"],
    "Madagascar": ["Ariary", "MGA"],
    "Malawi": ["Kwacha", "MWK"],
    "Malaysia": ["Ringgit", "MYR"],
    "Maldives": ["Rufiyaa", "MVR", "ރ."],
    "Malta": ["Lira", "MTL", "₤"],
    "Mauritania": ["Ouguiya", "MRO"],
    "Mauritius": ["Rupee", "MUR"],
    "Mexico": ["Peso", "MXN", "$"],
    "Moldova": ["Leu", "MDL"],
    "Mongolia": ["Tugrik", "MNT", "₮"],
    "Morocco": ["Dirham", "MAD", "د.م."],
    "Mozambique": ["New Metical", "MZN", "MT"],
    "Myanmar": ["Kyat", "MMK"],
    "Namibia": ["Dollar", "NAD", "$"],
    "Nepal": ["Rupee", "NPR"],
    "Netherlands": ["Guilder", "NLG"],
    "New Zealand": ["Dollar", "NZD", "$"],
    "Nicaragua": ["Cordoba Oro", "NIO", "C$"],
    "Nigeria": ["Naira", "NGN", "₦"],
    "North Korea": ["Won", "KPW", "₩"],
    "Norway": ["Kroner", "NOK"],
    "Oman": ["Rial", "OMR", "ر.ع."],
    "Pakistan": ["Rupee", "PKR"],
    "Panama": ["Balboa", "PAB"],
    "Papua New Guinea": ["Kina", "PGK"],
    "Paraguay": ["Guarani", "PYG", "₲"],
    "Peru": ["Nuevo Sol", "PEN"],
    "Philippines": ["Peso", "PHP", "₱"],
    "Poland": ["Zloty", "PLN", "zł"],
    "Portugal": ["Escudo", "PTE"],
    "Qatar": ["Rial", "QAR", "ر.ق"],
    "Romania": ["New Lei", "RON", "lei"],
    "Russia": ["Rouble", "RUB", "₽"],
    "Rwanda": ["Franc", "RWF"],
    "Samoa": ["Tala", "WST", "WS$"],
    "Sao Tome/Principe": ["Dobra", "STD"],
    "Saudi Arabia": ["Riyal", "SAR", "ر.س"],
    "Serbia": ["Dinar", "RSD", "дин. or din."],
    "Seychelles": ["Rupee", "SCR"],
    "Sierra Leone": ["Leone", "SLL"],
    "Singapore": ["Dollar", "SGD", "$"],
    "Slovakia": ["Koruna", "SKK"],
    "Slovenia": ["Tolar", "SIT"],
    "Solomon Islands": ["Dollar", "SBD", "$"],
    "Somali": ["Shilling", "SOS"],
    "South Africa": ["Rand", "ZAR"],
    "South Korea": ["Won", "KRW", "₩"],
    "Spain": ["Peseta", "ESP"],
    "Sri Lanka": ["Rupee", "LKR"],
    "St Helena": ["Pound", "SHP", "£"],
    "Sudan": ["Pound", "SDG", "ج.س."],
    "Suriname": ["Dollar", "SRD", "$"],
    "Swaziland": ["Lilangeni", "SZL"],
    "Sweden": ["Krona", "SEK"],
    "Syria": ["Pound", "SYP", "£ or ل.س"],
    "Taiwan": ["Dollar", "TWD", "NT$"],
    "Tanzania": ["Shilling", "TZS"],
    "Thailand": ["Baht", "THB", "฿"],
    "Tonga": ["Pa'anga", "TOP", "T$"],
    "Trinidad/Tobago": ["Dollar", "TTD", "TT$"],
    "Tunisia": ["Dinar", "TND", "د.ت"],
    "Turkey": ["New Lira", "TRY", "₺"],
    "Turkmenistan": ["Manat", "TMM"],
    "Uganda": ["Shilling", "UGX"],
    "Ukraine": ["Hryvnia", "UAH", "₴"],
    "Uruguay": ["Peso", "UYU", "$U"],
    "United Arab Emirates": ["Dirham", "AED", "د.إ"],
    "Vanuatu": ["Vatu", "VUV"],
    "Venezuela": ["Bolivar", "VEB"],
    "Vietnam": ["Dong", "VND", "₫"],
    "Yemen": ["Rial", "YER", "﷼"],
    "Zambia": ["Kwacha", "ZMK"],
    "Zimbabwe": ["Dollar", "ZWD", "$"],
}
